name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
        
    - name: Decode google-services.json
      run: 'echo ${{ secrets.GOOGLE_SERVICES_JSON }} | base64 -d > ./android_code/app/google-services.json'


    - name: Grant execute permission for gradlew
      working-directory: ./android_code
      run: chmod +x gradlew
    - name: Build with Gradle
      working-directory: ./android_code
      run: ./gradlew build -Pandroid.enableLint=false
